### ISSUE TITLE
Over/under keyboard in portrait

### ISSUE THREAD

**Issue by coreyfro** [mauiaaron/apple2#13]
Hey Apple2IX team!

I am super excited about your new project.  I am interested in using this app for the untapped wealth of education games from the 80's which are still relevant, today.  I am interested in including this app with a Free OSS builds of Android and Linux for various hardware platforms (OLPC, Raspberry Pi, Rootable Android devices such as the Amazon Fire) and I have been tinkering with Linapple for a while, but it's great to see new development for this still peerless education platform.

Right now, my focus is for Android.  We have jailbroken Amazon Fire 7's in the hands of students around the world, running http://sugarizer.org/ and accessing various offline internet platforms for remote locations.  Adding this app would be a treat for all.

I understand it might not, otherwise, be a priority, but would you consider a portrait interface allowing users to access your various HID devices without obstructing the Apple 2 screen?  I understand that this is mainly for gaming, but education gaming is generally typing oriented.

**Comment by mauiaaron** [comment]
This is awesome, I would definitely like to see this work out!  If I understand correctly you would like to have the app in portrait mode so you can keep both the software touch keyboard and Apple //e screen visible/active simultaneously?  I can probably slate this for the release-after-next of the Android version--likely 1.1.7--if not sooner.

**Comment by coreyfro** [comment]
That's right.  Infact, given the aspect ratios of the Apple2e screen, the
keyboard, and the average android phone, I bet an area for the joystick
could be could be presented, as well.

Thank you very much for considering this!

On Wed, Jan 20, 2016 at 8:21 PM, Aaron Culliney <notifications@github.com>
wrote:

> This is awesome, I would definitely like to see this work out! If I
> understand correctly you would like to have the app in portrait mode so you
> can keep both the software touch keyboard and Apple //e screen
> visible/active simultaneously? I can probably slate this for the
> release-after-next of the Android version--likely 1.1.7--if not sooner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mauiaaron/apple2/issues/13#issuecomment-173447090>.
>



-- 
Everything should be made as simple as possible, but no simpler - Albert
Einstein <http://en.wikipedia.org/wiki/Albert_Einstein>
Simplicity is the ultimate sophistication - Leonardo Da Vinci
<http://en.wikipedia.org/wiki/Leonardo_Da_Vinci>
Perfection is reached not when there is nothing left to add, but when there
is nothing left to take away - Antoine de Saint Exupéry
<http://en.wikipedia.org/wiki/Antoine_de_Saint_Exup%C3%A9ry>
Keep It Simple Stupid - Kelly Johnson
<http://en.wikipedia.org/wiki/Clarence_Johnson>

**Comment by mauiaaron** [comment]
A preliminary version of portrait mode is being tested at the moment and will make it into the next Android release.  The joystick will not be operable at the same time as the keyboard in this release, but that is on the drawing board ;-)

**Comment by coreyfro** [comment]
YAY!!! I just tested it out!  This is super exciting, I can't wait to demo
it!

On Wed, Feb 17, 2016 at 11:54 PM, Aaron Culliney <notifications@github.com>
wrote:

> A preliminary version of portrait mode is being tested at the moment and
> will make it into the next Android release. The joystick will not be
> operable at the same time as the keyboard in this release, but that is on
> the drawing board ;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mauiaaron/apple2/issues/13#issuecomment-185585105>.
>



-- 
Everything should be made as simple as possible, but no simpler - Albert
Einstein <http://en.wikipedia.org/wiki/Albert_Einstein>
Simplicity is the ultimate sophistication - Leonardo Da Vinci
<http://en.wikipedia.org/wiki/Leonardo_Da_Vinci>
Perfection is reached not when there is nothing left to add, but when there
is nothing left to take away - Antoine de Saint Exupéry
<http://en.wikipedia.org/wiki/Antoine_de_Saint_Exup%C3%A9ry>
Keep It Simple Stupid - Kelly Johnson
<http://en.wikipedia.org/wiki/Clarence_Johnson>

**Comment by mauiaaron** [comment]
I am marking this as done and have created a new card for allow simultaneous use of keyboard and one other touch device (joystick or mouse) : https://github.com/mauiaaron/apple2/issues/20
