### ISSUE TITLE
./configure: No such file or directory

### ISSUE THREAD

**Issue by mmphosis** [mauiaaron/apple2#29]
from http://deadc0de.org/apple2ix/ and I quote ...

> Linux and UN*X desktop version(s)
>
> Currently you can ./configure, make, and make install from source… ;-)

Nope.  :(

**Comment by mauiaaron** [comment]
Correct.  First you will need to use the full GNU autotools to generate the `configure` script from `configure.ac` ... check out what `recconf.sh` does.  Regards,
