### ISSUE TITLE
emulator not recognizing ctrl key on bluetooth keyboard

### ISSUE THREAD

**Issue by cwpritt** [mauiaaron/apple2#30]
I am using the S_C Macro assembler in the apple2ix android emulator. one of the features of the assembler software is to type ctrl-I to move over to the next column of the assembly program a user is entering, thus making it easier to line up the code columns. when i type on ctrl-I on my bluetooth keyboard, nothing happens. the only way i can get ctrl-I to work is to use the virtual keyboard in the app which is a pain in the butt. Can you make the app recognize the ctrl key on the bluetooth keyboard.

thanks   
charles

**Comment by mauiaaron** [comment]
I tried to reproduce the issue on my Bluetooth keyboard in both the latest store release and private branch and ctrl pressing is working fine.

This may be a device issue with your specific BT keyboard.  If possible try another keyboard to see if problem persists.

Regards,

**Comment by mauiaaron** [comment]
Triaging due to cannot reproduce issue.  Feel free to re-open if you have a repro test case.
